" My currently working version Vimrc
" I kept all other settings in plugins/settings directory
"

" Pathogen load
filetype off

" To disable a plugin, add it's bundle name to the following list
let g:pathogen_disabled = ['snipmate', 'pyflakes-vim', 'taglist.vim', 'vim-powerline', 'ropevim', 'jedi-vim', 'jshint']

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on
syntax on

runtime bundle/vim-pathogen/autoload/pathogen.vim

" special for different OS
if has('win32')
  " settings for win32
elseif has('unix')
  let shell='/bin/bash'
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
    " settings for MacOSX
  else
    " settings for linux
  endif
endif

" hit enter to cancel searched highlight
nnoremap <CR> :nohlsearch<CR>
" If there is a new window opened by QuickFix,
" restore the original <CR> behavior in that buffer.
autocmd BufReadPost quickfix nnoremap <buffer> <CR> <CR>

" select ALL
map <C-A> ggVG

" force myself to not to use the arrow keys
map <UP> <NOP>
map <DOWN> <NOP>
map <LEFT> <NOP>
map <RIGHT> <NOP>
inoremap <UP> <NOP>
inoremap <DOWN> <NOP>
inoremap <LEFT> <NOP>
inoremap <RIGHT> <NOP>

nnoremap <silent> <F2> :NERDTreeMirrorToggle<CR>

" Add external paths into ctags
" set tags+=/usr/local/lib/python2.7/dist-packages/tags

set hlsearch                          " search highlighting
set incsearch                         " incremental search
syntax enable
set synmaxcol=250                     " give up syntax highlighting after that col
set t_Co=256
set encoding=utf-8
set lazyredraw
set maxmempattern=2000

" Highlight the 81th char if the line is too long
" If you want to change the highlight color, change the theme's 'ColorColumn'
" Only for: markdown
autocmd FileType mkd call matchadd('ColorColumn', '\%81v', 100)

" Airline & Powerline settings
let g:airline_powerline_fonts = 1
"let g:Powerline_symbols = "fancy"
let g:airline_theme="terrytangyuan"

" Colorscheme settings
let g:solarized_termcolors=256
"let g:solarized_termtrans=1
"set background=light
colorscheme zenburn-colorful

" ====================
" Python settings
" NOTE: For TensorFlow
au FileType python set shiftwidth=2
au FileType python set softtabstop=2
au FileType python setlocal textwidth=80

" ====================
" Python-mode settings

" Load show documentation plugin, 0=off 1=on
let g:pymode_doc = 1
let g:pymode_doc_bind = 'K'

" Turn off pymode-pylint
let g:pymode_lint = 0
" disable pep8 from checker
let g:pymode_lint_checker = "pylint"
" disable 80 char column
let g:pymode_options_colorcolumn = 0
" use folding function from py-mode
let g:pymode_folding = 1
" Enable automatic virtualenv detection
let g:pymode_virtualenv = 1

" Disable auto-remove unused whitespaces.
let g:pymode_utils_whitespaces = 0

" pyflakes
"autocmd FileType python map <buffer> <c-F7> :call Flake8()<CR>

" Unload run code plugin
let g:pymode_run = 0

" Key for run python code
"let g:pymode_run_key = '<leader>r'

" Load breakpoints plugin
let g:pymode_breakpoint = 1

" Key for set/unset breakpoint
let g:pymode_breakpoint_key = '<leader>b'
let g:pymode_breakpoint_cmd = "import ipdb;ipdb.set_trace() # Set breakpoint_by_jiang"

" rope
" disable rope in python-mode
let g:pymode_rope = 0
" set up ropevim installed by myself
let g:ropevim_enable_autoimport=1
" add the name of modules you want to autoimport
let g:ropevim_autoimport_modules = ["os", "django"]
let g:pymode_rope_completion = 0
let g:pymode_rope_complete_on_dot = 0

" ====================
" Syntastic
" When set to 1 the cursor will always jump to the first issue detected.
let g:syntastic_auto_loc_list = 0
" Select my syntastic checker
let g:syntastic_python_checkers = ['flake8']
" Warning / Error codes: https://pypi.python.org/pypi/flake8/1.2
" NOTE: Ignore E111 & E114 is for TensorFlow, who uses only 2 spaces for indentation.
"       Remove these later.
let g:syntastic_python_flake8_args = '--ignore="E111,E114" --max-line-length=80'

" Use jshint (uses ~/.jshintrc)
" let g:syntastic_javascript_checkers = ['jshint']

" Better :sign interface symbols
" let g:syntastic_error_symbol = '✗'
" let g:syntastic_warning_symbol = '!'

" Syntastic for Go
let g:syntastic_go_checkers = ['govet', 'errcheck', 'go']

" ====================
" ConqueTerm
" Change some key bindings
let g:ConqueTerm_SendFileKey = '<c-F10>'
let g:ConqueTerm_SendVisKey = '<c-F9>'
let g:ConqueTerm_ExecFileKey = '<c-F11>'
let g:ConqueTerm_ToggleKey = '<c-F8>'

" ====================
" Markdown-vim
" disable its auto folding
let g:vim_markdown_folding_disabled=1

" ====================
" BufExplore
map <F3> :BufExplorer<CR>

" Disable beep and flash
set noeb vb t_vb=

" ====================
" Toggle the :Errors (quickfix) window
" Map to <leader>e
function! ToggleErrors()
    if empty(filter(tabpagebuflist(), 'getbufvar(v:val, "&buftype") is# "quickfix"'))
        " No location/quickfix list shown, open syntastic error location panel
        Errors
    else
        lclose
    endif
endfunction
nnoremap <silent> <leader>e :<C-u>call ToggleErrors()<CR>

" ====================
" Tagbar
nmap <F4> :TagbarToggle<CR>

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
    \ }

" ====================
" vim-gitgutter
" Turn off vim-gitgutter by default
let g:gitgutter_enabled = 0
" To disable all key mappings
let g:gitgutter_map_keys = 0
nmap <leader>] :GitGutterToggle<CR>

" ====================
" Folding settings
set foldmethod=syntax
set foldnestmax=1       "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=0

" ====================
" vim-go
" tutorial: https://github.com/fatih/vim-go-tutorial
let g:go_autodetect_gopath = 1
let g:go_auto_type_info = 1
let g:godef_split = 2

let g:go_highlight_functions = 1
" let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_fmt_command = "goimports"  "auto import when saving

" vim-go native checking
" let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
" let g:go_metalinter_autosave = 1
" let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'errcheck']
" let g:go_metalinter_deadline = '5s'

au FileType go nmap <leader>r <Plug>(go-run)
"au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>d <Plug>(go-def)

" ====================
" Supertab
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabClosePreviewOnPopupClose = 1

" ====================
" you-complete-me
let g:ycm_min_num_of_chars_for_completion = 2
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_collect_identifiers_from_tags_files = 1
if has($VIRTUAL_ENV)
  let g:ycm_python_binary_path = system('which python | tr -d "\r\n"')
endif
nnoremap <Leader>d :YcmCompleter GoTo<CR>

" ====================
" nerdcommenter
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
" Fit for python-mode default 'commentstring'
au FileType python let g:NERDSpaceDelims = 0

" ====================
" Bash settings
" use tab for indentation
" http://vim.wikia.com/wiki/Indent_with_tabs,_align_with_spaces
au FileType sh set noexpandtab

" a Tab2Space and a Space2Tab command that convert leading whitespace
" http://vim.wikia.com/wiki/VimTip1592
command! -range=% -nargs=0 Tab2Space execute '<line1>,<line2>s#^\t\+#\=repeat(" ", len(submatch(0))*' . &ts . ')'
command! -range=% -nargs=0 Space2Tab execute '<line1>,<line2>s#^\( \{'.&ts.'\}\)\+#\=repeat("\t", len(submatch(0))/' . &ts . ')'

" ====================
" jshint
let g:JSHintHighlightErrorLine = 0  " disable error highlighting

" ====================
" mark (Mark--Karkat)
" Remap to avoid <leader>r conflict with 'align' plugin
nmap <unique> <silent> <Leader>mr <Plug>MarkRegex
vmap <unique> <silent> <Leader>mr <Plug>MarkRegex

" ====================
" Damian-Conway-s-Vim-Setup plugins
" vmath.vim
vmap <silent><expr>  ++  VMATH_YankAndAnalyse()
" dragvisuals.vim
vmap  <expr>  <S-LEFT>   DVB_Drag('left')
vmap  <expr>  <S-RIGHT>  DVB_Drag('right')
vmap  <expr>  <S-DOWN>   DVB_Drag('down')
vmap  <expr>  <S-UP>     DVB_Drag('up')
